### ISSUE TITLE
Hide TMPE crosswalks V3.2 [stable] ERROR

### ISSUE THREAD

**Issue by ghost** [kianzarrin/PedestrianBridge#10]
Hello all, 

a really great mode, using it for long now. The problem started some time back when the error box started to appear, referring to this mod.

I tried a new game with only TMPE and this mode and still the same error appeared. When using only TMPE everything works fine, this error appears only after enabling "Hide TMPE crosswalks" mod.

Also on first load on saved city file or a new game there is no error, the error only appears after second load from save file.

Can´t imagine playing this game without this mode :( Sorry for my bad english.

Thank you for your help.

[HideCrosswalks.log](https://github.com/kianzarrin/PedestrianBridge/files/8986264/HideCrosswalks.log)
[output_log.txt](https://github.com/kianzarrin/PedestrianBridge/files/8986265/output_log.txt)
.

**Comment by kianzarrin** [comment]
is this resolved?

**Comment by ghost** [comment]
Yeah, I switched to blank roads 🙂 Huge respect for modding and active roll
in CS comunity.

Dňa ut 27. 9. 2022, 9:49 kianzarrin ***@***.***> napísal(a):
