### ISSUE TITLE
Reddit article Hide TMPE Crossings 3.0

### ISSUE THREAD

**Issue by RaeTheGit** [kianzarrin/PedestrianBridge#5]
### What is this?

**kian.zarrin** has been favouring us with quite a few mods recently, all somewhat related to the TMPE[link to workshop page] hemisphere. The probably most important one to many of us is the Hide TMPE Crosswalks[link to workshop page] Mod which basically hides crosswalks (wow, who would have thought that!) when they are disabled via TMPE junction restrictions. Additionally, Hide TMPE Crosswalks also integrates with Network Skins 2[link to workshop page] which will show a button to hide a crosswalk **regardless** of TMPE junction restrictions as seen on the picture below. _Be aware that this only hides the crosswalk texture. It does NOT disable the ability of your Cims to cross the street!_
![NS2_integration](https://user-images.githubusercontent.com/65011289/82820841-3be5df80-9ea3-11ea-8aa2-8f3896f14a56.png)
Integration of Hide TMPE Ctrosswalks into Network Skins 2

### So how and where can I use this other than for purely cosmetic reasons? How does it integrate with TMPE, which it has obviously primarily been designed for?
As a TMPE user you will probably know the ability to stop your Cims from using crosswalks via **junction restrictions** as seen below:
![TMPE_junction_rest_crosswalk](https://user-images.githubusercontent.com/65011289/82820838-3b4d4900-9ea3-11ea-83be-c50fe77eee8d.png)
TMPE junction restrictions tool to dis- or enable crosswalks

It always bothered me (and others) that they were still visible and there were only two ways to be sure if a crossing is disabled or not. One is to activate TMPE with its junction restriction tool so the restrictions overlay would be visible which needs at least two clicks to get there. The other is to permanently enable the restrictions overlay in TMPE options menu which doesn't need any additional clicks but cloggs up the view with information that most of the time isn't needed or even isn't relevant at all. Aside of usability and gameplay convenience, aesthetics and realism are anonther issue. Why should there be crosswalk paintings on the road if people aren't allowed to cross? That doesn't make sense, right?

This is where **Hide TMPE Crosswalks** is waiting to come for the rescue! As soon as it detects that a crossing is disabled, it sends out a crew of fast-as-light road maintainer superheroes to eradicate any traces of what might have given a hint to crossings ever being possible at that place.
![Crossings_disabled](https://user-images.githubusercontent.com/65011289/82820843-3c7e7600-9ea3-11ea-868b-f10f2dd2b249.png)
Two of three crossings disabled and crossing texture removed from junction.

On a more technical side, this mod re-renders the part of the road where the crossing texture would be, but without it - obviously. In practice, this means that some of your resources are needed to render the new road look and to store this in memory, so under unfavourable circumstances this mod can and will lower overall game performance. I.e. if your computer is just barely able to run Cities:Skylines, you should maybe think twice before using this mod. From experience I can say, though, a multicore CPU with 3GHz+, _at least_ 8GB of RAM and a half decent graphics card (2GB of VRAM or more) should be able to handle this mod very well unless you go totally crazy with installed mods and assets.
To reduce the impact on game performance, the re-rendered parts for each road asset are cached so if you ban crossings on the same road asset over and over again, the rendering is only done and stored once. It also means, if you use 50 different road assets and prohibit crossing on each of them only once, it will re-render 50 times and it will store the rendering result 50 times and there is hardly any difference between disallowing the crossing only once or a hundred times per road. For a more detailed in-depth description of the technical side and possible issues, please refer to the steam workshop page[link to workshop page] for this mod.

One thing to note is, that if you zoom out far enough, the crossings will reappear visually. This is due to how the game rendering engine handles detail levels at a distance, but can be influenced with boformer's ULOD mod[link to workshop page].

**Comment by kianzarrin** [comment]
This is a very good article. Its more useful in the context  ofhttps://community.simtropolis.com/forums/forum/270-cities-skylines/ , http://www.citiesmods.com/ or http://smods.ru/  . It also could be useful as wiki page. 

Reddit post on the other hand should be a short and to the point. article with all the details spared (user can click on the item link and see more info). Its more like a highlight not a tutorial. Animated gif (if supported) could be used for before/after picture.

if you click on the release tag you will see how other release posts look like. They are mostly a a couple of  lines long with a picture. The biggest one I found was the TMPE release:
https://www.reddit.com/r/CitiesSkylinesModding/comments/fynulc/tmpe_1130_labs/

Hide TMPE crosswalks does not do much. So it does not need much explanation.

So it would be nice to keep the article short and to the point and mention the following in a compact form (ordered by importance):
- it hide crosswalks with a beautiful picture (see screenshots in the asset page the asym roads seem to look very attractive).
- it works with TMPE interface (the picture you above explains it nicely)
- it smooths out the textures.
- mention node controller for more ways to manage crossings.
