### ISSUE TITLE
Ped Bridge builder doesn't seem to recognize Parklife or Campus paths

### ISSUE THREAD

**Issue by Allystrya** [kianzarrin/PedestrianBridge#6]
So I was doing a demo video but was avoiding my custom paths when I realized all of the paths were looking the same except the gravel path.  It isn't acknowledging Parklife or Campus paths but defaulting those to the regular pavement elevated path.  My custom workshop paths the builder had no issues with.

I thought maybe it was a mod conflict but I loaded my vanilla city on a completely different computer with it's own account and got the same results.

Here is a video showing the issue:  https://youtu.be/egNXBgQa8ZY

Here is the log from my main computer that is modded
[PedestrianBridge 01.txt](https://github.com/kianzarrin/PedestrianBridge/files/4679273/PedestrianBridge.01.txt)

Here is the log from my second computer unmodded
[PedestrianBridge 2nd Comp.txt](https://github.com/kianzarrin/PedestrianBridge/files/4679276/PedestrianBridge.2nd.Comp.txt)

**Comment by kianzarrin** [comment]
is this resolved?
