### ISSUE TITLE
Tunnel at roundabout does not go under roads.

### ISSUE THREAD

**Issue by rjshaver** [kianzarrin/PedestrianBridge#9]
I am not sure if this is caused by another mod or if this occurs with minimal mods.  I would make a roundabout with the roundabout builder.  Afterward, I decided to try to put a pedestrian bridge in tunnel mode at the roundabout.  I looked at the result and the tunnels were curved between roads but did not go under the road.  It was just the opposite as I would have expected.

Can someone else test this?  If you do not understand, please respond and I will take a screen pic.  

Thanks for your work.  The above ground elevated bridges work great.

**Comment by kianzarrin** [comment]
is this resolved?

**Comment by rjshaver** [comment]
I had not tested it in a while, but it is working now.  Thanks.
